name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: ubuntu-22.04

    steps:
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.organization=kshyk
            -Dsonar.projectKey=kshyk_api-tests
            -Dsonar.sources=.
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.coverage.jacoco.xmlReportPaths=**/jacocoTestReport.xml
